# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimediaWidgets import QVideoWidget
from PyQt5.QtMultimedia import QMediaPlayer, QMediaContent


# 鼠标绘画事件
class MyLabel(QtWidgets.QLabel):
    def __init__(self, parent=None):
        super(MyLabel, self).__init__(parent)
        self.x0, self.y0 = 0, 0  # 鼠标按下的初始位置
        self.x1, self.y1 = 0, 0  # 鼠标当前位置
        self.flag = False  # 鼠标是否按下
        self.move = False  # 是否在移动状态

    def mousePressEvent(self, event):
        if event.button() == QtCore.Qt.LeftButton:
            self.x0, self.y0 = event.pos().x(), event.pos().y()
            self.flag = True

    def mouseMoveEvent(self, event):
        if self.flag:
            self.move = True
            self.x1, self.y1 = event.pos().x(), event.pos().y()
            self.update()

    def mouseReleaseEvent(self, event):
        if event.button() == QtCore.Qt.LeftButton:
            self.flag = False
            self.move = False

    def paintEvent(self, event):
        super().paintEvent(event)
        if self.flag and self.move:
            painter = QtGui.QPainter(self)
            painter.setPen(QtGui.QPen(QtCore.Qt.red, 2, QtCore.Qt.SolidLine))
            painter.drawRect(QtCore.QRect(self.x0, self.y0, self.x1 - self.x0, self.y1 - self.y0))



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1618, 947)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/icons/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setStyleSheet("""
QMainWindow {
    background-color: #f1f1f3;
}
QWidget {
    color: #2d2d32;
    font: 11pt 'Microsoft YaHei';
}
QFrame#frame, QFrame#frame_2, QFrame#infoCard, QFrame#shortcutsCard, QFrame#labelsCard {
    background-color: transparent;
}
QFrame#frame_2, QFrame#infoCard, QFrame#shortcutsCard, QFrame#labelsCard {
    background-color: #f9f9fb;
    border-radius: 16px;
    border: 1px solid #d9d9de;
    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.03);
}
QComboBox {
    background-color: #ffffff;
    border: 1px solid #c8c8ce;
    border-radius: 10px;
    padding: 6px 12px;
}
QComboBox:hover {
    border-color: #a0a0a8;
}
QLabel#titleLabel {
    font: 600 16pt 'Microsoft YaHei';
    color: #1f1f25;
}
QLabel[class="sectionTitle"] {
    font: 600 12pt 'Microsoft YaHei';
    color: #34343a;
    margin-bottom: 6px;
}
QPushButton {
    background-color: #f5f5f7;
    border: 1px solid #d0d0d8;
    border-radius: 10px;
    padding: 9px 16px;
    color: #2e2e35;
}
QPushButton:hover:enabled {
    background-color: #e7e7eb;
    border-color: #b8b8c2;
}
QPushButton:disabled {
    color: #a4a4ac;
    border-color: #e1e1e6;
}
QListWidget {
    background-color: #ffffff;
    border: 1px solid #dcdcE2;
    border-radius: 14px;
    padding: 14px;
}
QListWidget::item {
    padding: 8px 10px;
    border-radius: 8px;
}
QListWidget::item:selected {
    background-color: #d9dde5;
    color: #1f1f25;
}
QProgressBar {
    border: 1px solid #dcdcE2;
    border-radius: 12px;
    background-color: #f5f5f7;
    padding: 3px;
    text-align: center;
    color: #2d2d32;
}
QProgressBar::chunk {
    background-color: #a5adc4;
    border-radius: 10px;
}
QSlider::groove:horizontal {
    height: 4px;
    border-radius: 2px;
    background: #d7d7dd;
}
QSlider::handle:horizontal {
    width: 14px;
    background: #a3a3ab;
    border-radius: 7px;
    margin: -5px 0;
}
QLabel#shortcutDetails {
    line-height: 1.5em;
    color: #5a5a62;
}
QFrame#viewerFrame {
    background-color: #fefefe;
    border-radius: 18px;
    border: 1px solid #dcdcE2;
}
        """)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.frame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.viewerAreaLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.viewerAreaLayout.setContentsMargins(0, 0, 0, 0)
        self.viewerAreaLayout.setSpacing(0)

        self.viewerFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.viewerFrame.setObjectName("viewerFrame")
        self.viewerFrame.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.viewerStack = QtWidgets.QStackedLayout(self.viewerFrame)
        self.viewerStack.setStackingMode(QtWidgets.QStackedLayout.StackAll)
        self.viewerStack.setContentsMargins(18, 18, 18, 18)

        self.label_3 = QtWidgets.QLabel(self.viewerFrame)
        self.label_3.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setStyleSheet("background-color: transparent;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.viewerStack.addWidget(self.label_3)

        self.videoLayout = QtWidgets.QVBoxLayout(self.label_3)
        self.videoLayout.setContentsMargins(0, 0, 0, 0)
        self.videoLayout.setSpacing(0)

        self.videoWidget = QVideoWidget(self.label_3)
        self.videoWidget.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.videoLayout.addWidget(self.videoWidget)

        self.mediaPlayer = QMediaPlayer()
        self.mediaPlayer.setVideoOutput(self.videoWidget)

        self.viewerAreaLayout.addWidget(self.viewerFrame)

        self.label_4 = None
        self.disableLabel4()

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setMinimumWidth(320)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")

        MainWindow.setCentralWidget(self.centralwidget)
        self.setSplitterSizes()

        self.infoCard = QtWidgets.QFrame(self.layoutWidget)
        self.infoCard.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.infoCard.setObjectName("infoCard")
        self.infoLayout = QtWidgets.QVBoxLayout(self.infoCard)
        self.infoLayout.setContentsMargins(20, 20, 20, 20)
        self.infoLayout.setSpacing(12)
        self.infoLayout.setObjectName("infoLayout")
        self.titleLabel = QtWidgets.QLabel(self.infoCard)
        self.titleLabel.setObjectName("titleLabel")
        self.infoLayout.addWidget(self.titleLabel)
        self.label = QtWidgets.QLabel(self.infoCard)
        self.label.setObjectName("label")
        self.label.setProperty("class", "sectionTitle")
        self.infoLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.infoCard)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.infoLayout.addWidget(self.comboBox)
        self.currentImageLabel = QtWidgets.QLabel(self.infoCard)
        self.currentImageLabel.setObjectName("currentImageLabel")
        self.currentImageLabel.setWordWrap(True)
        self.infoLayout.addWidget(self.currentImageLabel)
        self.verticalLayout.addWidget(self.infoCard)

        self.frame_2 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # 添加进度条
        self.progressBar = QtWidgets.QProgressBar(self.frame_2)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setValue(0)
        self.progressBar.hide()  # 初始状态隐藏
        self.verticalLayout_2.addWidget(self.progressBar)

        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.label_5.setProperty("class", "sectionTitle")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_2)
        self.horizontalSlider.setEnabled(False)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_2.addWidget(self.horizontalSlider)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setEnabled(False)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)

       # 添加"视频打标"标签
        self.label_video_marking = QtWidgets.QLabel(self.frame_2)
        self.label_video_marking.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_video_marking.setObjectName("label_video_marking")
        self.label_video_marking.setProperty("class", "sectionTitle")
        self.verticalLayout_2.addWidget(self.label_video_marking)

        # 添加"开始检测打标"按钮
        self.pushButton_start_marking = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_start_marking.setEnabled(False)
        self.pushButton_start_marking.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_start_marking.setObjectName("pushButton_start_marking")
        self.verticalLayout_2.addWidget(self.pushButton_start_marking)

        self.verticalLayout.addWidget(self.frame_2)
        self.labelsCard = QtWidgets.QFrame(self.layoutWidget)
        self.labelsCard.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelsCard.setObjectName("labelsCard")
        self.labelsLayout = QtWidgets.QVBoxLayout(self.labelsCard)
        self.labelsLayout.setContentsMargins(20, 20, 20, 20)
        self.labelsLayout.setSpacing(12)
        self.labelsLayout.setObjectName("labelsLayout")
        self.label_2 = QtWidgets.QLabel(self.labelsCard)
        self.label_2.setObjectName("label_2")
        self.label_2.setProperty("class", "sectionTitle")
        self.labelsLayout.addWidget(self.label_2)
        self.listWidget = QtWidgets.QListWidget(self.labelsCard)
        self.listWidget.setObjectName("listWidget")

        self.listWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.labelsLayout.addWidget(self.listWidget)
        self.verticalLayout.addWidget(self.labelsCard)

        self.shortcutsCard = QtWidgets.QFrame(self.layoutWidget)
        self.shortcutsCard.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.shortcutsCard.setObjectName("shortcutsCard")
        self.shortcutsLayout = QtWidgets.QVBoxLayout(self.shortcutsCard)
        self.shortcutsLayout.setContentsMargins(20, 20, 20, 20)
        self.shortcutsLayout.setSpacing(10)
        self.shortcutsLayout.setObjectName("shortcutsLayout")
        self.shortcutsTitle = QtWidgets.QLabel(self.shortcutsCard)
        self.shortcutsTitle.setObjectName("shortcutsTitle")
        self.shortcutsTitle.setProperty("class", "sectionTitle")
        self.shortcutsLayout.addWidget(self.shortcutsTitle)
        self.shortcutDetails = QtWidgets.QLabel(self.shortcutsCard)
        self.shortcutDetails.setObjectName("shortcutDetails")
        self.shortcutDetails.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.shortcutDetails.setWordWrap(True)
        self.shortcutDetails.setTextFormat(QtCore.Qt.RichText)
        self.shortcutsLayout.addWidget(self.shortcutDetails)
        self.verticalLayout.addWidget(self.shortcutsCard)
        self.verticalLayout.addStretch(1)
        self.horizontalLayout_2.addWidget(self.splitter)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1618, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Dir = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("GUI/icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Dir.setIcon(icon1)
        self.actionOpen_Dir.setObjectName("actionOpen_Dir")

        self.actionOpen_Dir.triggered.connect(self.enableLabel4)

        self.actionChange_Save_Dir = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("GUI/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionChange_Save_Dir.setIcon(icon2)
        self.actionChange_Save_Dir.setObjectName("actionChange_Save_Dir")
        self.actionNext_Image = QtWidgets.QAction(MainWindow)
        self.actionNext_Image.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("GUI/icons/next.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext_Image.setIcon(icon3)
        self.actionNext_Image.setObjectName("actionNext_Image")
        self.actionPrev_Image = QtWidgets.QAction(MainWindow)
        self.actionPrev_Image.setEnabled(False)
        self.actionVideo_marking = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("GUI/icons/Video_marking.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVideo_marking.setIcon(icon7)
        self.actionVideo_marking.setObjectName("actionVideo_marking")

        self.actionVideo_marking.triggered.connect(self.enableLabel4)

        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("GUI/icons/prev.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrev_Image.setIcon(icon4)
        self.actionPrev_Image.setObjectName("actionPrev_Image")
        self.actionCreate_RectBox = QtWidgets.QAction(MainWindow)
        self.actionCreate_RectBox.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("GUI/icons/create.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_RectBox.setIcon(icon5)
        self.actionCreate_RectBox.setObjectName("actionCreate_RectBox")
        self.actionOpen_Video = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("GUI/icons/video.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Video.setIcon(icon6)
        self.actionOpen_Video.setObjectName("actionOpen_Video")
        


        self.actionOpen_Video.triggered.connect(self.disableLabel4)

        MainWindow.addAction(self.actionOpen_Video)
        MainWindow.addAction(self.actionOpen_Dir)
        MainWindow.addAction(self.actionChange_Save_Dir)
        MainWindow.addAction(self.actionVideo_marking)
        MainWindow.addAction(self.actionNext_Image)
        MainWindow.addAction(self.actionPrev_Image)
        MainWindow.addAction(self.actionCreate_RectBox)
        

        self.splitter.setStretchFactor(0, 4)
        self.splitter.setStretchFactor(1, 1)
        QtCore.QTimer.singleShot(0, self.setSplitterSizes)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def setSplitterSizes(self):
        # 根据当前 splitter 的宽度设置比例
        total_size = self.splitter.size().width()
        if total_size <= 0:
            return
        size1 = int(0.8 * total_size)  # 第一个区域约占80%
        size2 = max(total_size - size1, 0)  # 第二个区域占剩余部分
        self.splitter.setSizes([size1, size2])

    def _setOverlay(self, overlay_widget):
        if self.label_4 is not None:
            self.viewerStack.removeWidget(self.label_4)
            self.label_4.deleteLater()

        overlay_widget.setParent(self.viewerFrame)
        overlay_widget.setMinimumSize(QtCore.QSize(0, 0))
        overlay_widget.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        overlay_widget.setStyleSheet("background-color: transparent;")
        overlay_widget.setObjectName("label_4")
        overlay_widget.setMouseTracking(True)
        self.viewerStack.addWidget(overlay_widget)
        self.label_4 = overlay_widget

    def enableLabel4(self):
        # 点击打开目录后启用 MyLabel
        overlay = MyLabel(self.viewerFrame)
        overlay.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self._setOverlay(overlay)

    def disableLabel4(self):
        overlay = QtWidgets.QLabel(self.viewerFrame)
        overlay.setAttribute(QtCore.Qt.WA_TransparentForMouseEvents, True)
        overlay.setText("")
        self._setOverlay(overlay)
        


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Auto Yolo Labeler"))
        self.titleLabel.setText(_translate("MainWindow", "Auto Yolo Labeler"))
        self.label.setText(_translate("MainWindow", "保存类型"))
        self.comboBox.setItemText(1, _translate("MainWindow", "XML"))
        self.comboBox.setItemText(0, _translate("MainWindow", "YOLO"))
        self.currentImageLabel.setText(_translate("MainWindow", "当前图片路径将在此显示"))
        self.label_2.setText(_translate("MainWindow", "标签"))
        self.label_5.setText(_translate("MainWindow", "视频："))
        self.pushButton.setText(_translate("MainWindow", "开始"))
        self.pushButton_2.setText(_translate("MainWindow", "暂停"))
        self.pushButton_3.setText(_translate("MainWindow", "抽帧"))
        self.pushButton_5.setText(_translate("MainWindow", "自动抽帧"))
        self.pushButton_4.setText(_translate("MainWindow", "重新播放"))
        self.label_video_marking.setText(_translate("MainWindow", "视频打标"))
        self.pushButton_start_marking.setText(_translate("MainWindow", "目标跟踪"))
        self.shortcutsTitle.setText(_translate("MainWindow", "快捷键提示"))
        self.shortcutDetails.setText(_translate("MainWindow", "<b>E</b> - 打开图片目录<br><b>S</b> - 设置保存目录<br><b>V</b> - 打开视频文件<br><b>W</b> - 创建标注矩形<br><b>A</b> / <b>D</b> - 上一张 / 下一张图片"))
        self.actionOpen_Dir.setText(_translate("MainWindow", "Open Dir"))
        self.actionOpen_Dir.setShortcut(_translate("MainWindow", "E"))
        self.actionChange_Save_Dir.setText(_translate("MainWindow", "Change Save Dir"))
        self.actionChange_Save_Dir.setShortcut(_translate("MainWindow", "S"))
        self.actionNext_Image.setText(_translate("MainWindow", "Next Image"))
        self.actionNext_Image.setShortcut(_translate("MainWindow", "D"))
        self.actionPrev_Image.setText(_translate("MainWindow", "Prev Image"))
        self.actionPrev_Image.setShortcut(_translate("MainWindow", "A"))
        self.actionCreate_RectBox.setText(_translate("MainWindow", "Create RectBox"))
        self.actionCreate_RectBox.setShortcut(_translate("MainWindow", "W"))
        self.actionOpen_Video.setText(_translate("MainWindow", "Open Video"))
        self.actionOpen_Video.setShortcut(_translate("MainWindow", "V"))
        self.actionVideo_marking.setText(_translate("MainWindow", "Video marking"))

